version: '3.9'

services:
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  migration:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - database
  cli:
    build: .
    environment:
      - DB_URL=postgres://postgres:postgres@database:5432/postgres
